// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0ac1af5b-9005-4598-9eca-9125bc470a80";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRoom1Change();
void onDoorSwitchChange();

CloudLight room1;
CloudSwitch doorSwitch;
int mq2;
int waterlevel;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(room1, READWRITE, ON_CHANGE, onRoom1Change);
  ArduinoCloud.addProperty(doorSwitch, READWRITE, ON_CHANGE, onDoorSwitchChange);
  ArduinoCloud.addProperty(mq2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(waterlevel, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
